name: Run Tests

# Controls when the action will run. 
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install apt dependencies
        run: |
            sudo add-apt-repository -y ppa:tricksterguy87/complx
            sudo apt update -qq
            sudo apt install -y castxml libpython3-dev libboost-python-dev liblc3-dev liblc3-plugins
            sudo ldconfig
      - name: Install python packages
        run: |
            pip3 install six wheel scikit-build pygccxml pyplusplus pylc3.core pylc3.autograder unittest2 parameterized
      - name: Run Tests
        run: |
            mkdir build && cd build
            cmake ..
            ctest -VV
